option(SAN_ADDRESS "Enable Address Sanitizer (Linux only)" OFF)
option(SAN_THREAD "Enable Thread Sanitizer (Linux/macOS)" OFF)
option(SAN_UB "Enable Undefined Behavior Sanitizer" OFF)

set(SANITIZER_ACTIVE OFF)

if (SAN_ADDRESS AND SAN_THREAD)
    message(WARNING "ASan and TSan are mutually exclusive. Disabling TSan.")
    set(SAN_THREAD OFF)
endif ()

if (SAN_THREAD AND SAN_UB)
    message(WARNING "TSan and UBSan may interact; disabling UBSan for TSan run.")
    set(SAN_UB OFF)
endif ()

if (SAN_ADDRESS)
    if (WIN32)
        message(WARNING "ASan disabled on Windows. SAN_ADDRESS forced OFF.")
        set(SAN_ADDRESS OFF)
    elseif (APPLE)
        message(WARNING "ASan disabled on macOS. SAN_ADDRESS forced OFF.")
        set(SAN_ADDRESS OFF)
    else ()
        message(STATUS "=== ASan enabled (Linux) ===")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fsanitize=address -fsanitize-address-use-after-scope")
        add_link_options("-fsanitize=address" "-fsanitize-address-use-after-scope")
        if (SAN_UB)
            set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fsanitize=undefined -fno-sanitize-recover=undefined")
            add_link_options("-fsanitize=undefined")
            message(STATUS "  UBSan: combined with ASan")
            set(SAN_UB OFF)
        endif ()
        set(SANITIZER_ACTIVE ON)
    endif ()
endif ()

if (SAN_THREAD)
    if (WIN32)
        message(WARNING "TSan disabled on Windows. SAN_THREAD forced OFF.")
        set(SAN_THREAD OFF)
    else ()
        message(STATUS "=== TSan enabled ===")
        add_compile_options("-fsanitize=thread")
        add_link_options("-fsanitize=thread")
        set(SANITIZER_ACTIVE ON)
    endif ()
endif ()

if (SAN_UB)
    message(STATUS "=== UBSan enabled ===")
    add_compile_options("-fsanitize=undefined" "-fno-sanitize-recover=undefined")
    add_link_options("-fsanitize=undefined")
    set(SANITIZER_ACTIVE ON)
endif ()

if (SANITIZER_ACTIVE)
    add_compile_definitions(SANITIZER_ENABLED=1)
endif ()
